---
- name: "AAP CasC Webhook triggered play"
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: "Get the modified files from all the received commits"
      set_fact:
        env: "{{ tower_webhook_payload.ref.split('/')[2] }}"
        orgs: "{{ tower_webhook_payload.project.name }}"
        list_of_files: "{{ ((tower_webhook_payload.commits | map(attribute='added') | list) +
                           (tower_webhook_payload.commits | map(attribute='modified') | list) +
                           (tower_webhook_payload.commits | map(attribute='removed') | list))
                       | flatten }}"
    - name: "Get the Organization and the tags to run the CasC"
      set_fact:
        org_files_dict: "{{ (org_files_dict | default({})) | combine({input_var[0]: ((org_files_dict[input_var[0]] | default([])) + [input_var[1]])}) }}"
      vars:
        input_var: "{{ item | regex_search('/([^/]*)/env/(?:[^/]*)/configure_controller_(.*).ya?ml', '\\1', '\\2') }}"
      loop: "{{ list_of_files }}"
      when: input_var | type_debug is match('list')
    - debug: var=org_files_dict

    # TODO: this job can be launched from the workflow directly (artifacts are needed)
    - name: "Run the CasC_JobTemplates_AAP_CI_Config_Controller Automation Platform Job to update the objects"
      tower_job_launch:
        controller_host: '{{ lookup("env", "CONTROLLER_HOST") }}'
        controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
        controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
        name: "{{ org_tags.key }} CasC_JobTemplates_AAP_CI_Config_Controller"
        extra_vars:
          orgs: "{{ org_tags.key }}"
          dir_orgs_vars: 'orgs_vars'
          ansible_python_interpreter: "/usr/bin/python3"
          env: "{{ env }}"
        tags: "{{ org_tags.value }}"
        validate_certs: no
        wait: yes
        verbosity: 0
      with_dict: "{{ org_files_dict }}"
      loop_control:
        loop_var: org_tags
      when: org_files_dict is defined

# ToDo -> Se han modificado ficheros, pero no relacionados con el CasC
...
