---
# Create Controller Execution Environments
- name: "AAP CasC Execution Environment Creation"
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  vars:
    controller_configuration_execution_environments_secure_logging: false
    controller_validate_certs: false
    controller_hostname: aapstdalone.bcnconsulting.com
    #controller_hostname: lbtower.bcnconsulting.com
    controller_username: admin
    controller_password: redhat00
    controller_execution_environments:
      - name: "My EE"
        image: automationhub.bcnconsulting.com/ee-casc
        pull: always
        credential: "Automation Hub Container Registry User"
        #credential: "Automation Hub Container Registry"
  tasks:
  - name: Add Controller Execution Environments
    execution_environment:
      name:                           "{{ __execution_environments_item.name | mandatory }}"
      description:                    "{{ __execution_environments_item.description | default(omit, true) }}"
      image:                          "{{ __execution_environments_item.image | mandatory }}"
      organization:                   "{{ __execution_environments_item.organization.name | default( __execution_environments_item.organization | default(omit, true)) }}"
      credential:                     "{{ __execution_environments_item.credential | default(omit, true) }}"
      pull:                           "{{ __execution_environments_item.pull | default(omit, true) }}"
      state:                          "{{ __execution_environments_item.state | default(controller_state | default('present')) }}"

      # Role specific options
      controller_username:            "{{ controller_username | default(omit, true) }}"
      controller_password:            "{{ controller_password | default(omit, true) }}"
      controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
      controller_host:                "{{ controller_hostname | default(omit, true) }}"
      controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
      validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
    loop: "{{ controller_execution_environments }}"
    loop_control:
      loop_var: "__execution_environments_item"
    no_log: "{{ controller_configuration_execution_environments_secure_logging }}"
    when: controller_execution_environments is defined
...
