---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    access_token: "yz-8VJcqnu491Fs4oLMM"
  tasks:
    - name: "Adding a project hook"
      community.general.gitlab_hook:
        api_url: https://gitlab.bcnconsulting.com
        api_token: "{{ access_token }}"
        project: "{{ gitlab_project }}"
        hook_url: "{{ webhook_url }}"
        state: present
        push_events: yes
        tag_push_events: yes
        hook_validate_certs: no
        token: "{{  webhook_token }}"
        validate_certs: false
        push_events_branch_filter: "{{ env }}"
...
#  ansible-playbook gitlab_webhook.yml -e '{ gitlab_project: "aap-demo/organization2", webhook_url: "https://aapstdalone.bcnconsulting.com/api/v2/workflow_job_templates/153/gitlab/", webhook_token: "FtT5oQeAQNpSHmigxAa7ROxzszgqplqkhCrKEZiImt4xLHbxaS", env: dev}'
#  ansible-playbook gitlab_webhook.yml -e '{ gitlab_project:"", webhook_url: "", webhook_token: "", env: ""}'
