---
# tasks file for tower_ldap_settings
- include_vars:
    file: "{{ item }}"
  loop:
    - "{{ dir_orgs_vars }}/configure_tower_general.yml"
    - "{{ dir_orgs_vars }}/configure_tower_credentials.yml"
    - "{{ dir_orgs_vars }}/{{ orgs }}/configure_tower_roles.yml"
  when: orgs is defined and dir_orgs_vars is defined

- name: Configure Tower Roles
  ansible.controller.tower_role:
    tower_username: "{{ configure_tower_username }}"
    tower_password: "{{ configure_tower_password }}"
    tower_host: "{{ configure_tower_server_url }}"
    validate_certs: "{{ configure_tower_validate_certs }}"
    user: "{{ item.user | default(omit) }}"
    target_team: "{{ item.target_team | default(omit) }}"
    team: "{{ item.team | default(omit) }}"
    project: "{{ item.project | default(omit) }}"
## admin, read,member, execute, adhoc,update, use, auditor, project_admin, inventory_admin, credential_admin, workflow_admin, notification_admin, job_template_admin ##
    role: "{{ item.role }}"
    organization: "{{ orgs }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ configure_tower_roles }}"
  when: configure_tower_roles is defined
  delegate_to: "{{ 'localhost' if tower_local else omit }}"
