---
- include_vars:
    file: "{{ item }}"
  loop:
    - "{{ dir_orgs_vars }}/configure_tower_credentials.yml"
    - "{{ dir_orgs_vars }}/configure_tower_general.yml"
    - "{{ dir_orgs_vars }}/{{ orgs }}/configure_tower_workflows.yml"
  when: orgs is defined and dir_orgs_vars is defined

- name: Create tower workflows
  ansible.controller.tower_workflow_template:
    tower_username: "{{ configure_tower_username }}"
    tower_password: "{{ configure_tower_password }}"
    tower_host: "{{ configure_tower_server_url }}"
    validate_certs: "{{ configure_tower_validate_certs }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    organization: "{{ item.org | default(orgs) }}"
    state: "{{ item.state | default('present') }}"
    schema: "{{ (lookup('file', dir_orgs_vars + '/' + orgs + '/schemas/' + item.schema_file) | from_yaml) if item.schema_file is defined else (item.schema if item.schema is defined else omit ) }}"
    survey_enabled: "{{ item.survey_enabled | default('no') }}"
    survey: "{{ lookup('file', dir_orgs_vars + '/' + orgs + '/surveys/' + item.survey_file) if item.survey_file is defined else omit }}"
    extra_vars: "{{ (lookup('file', item.extra_vars_path) | from_yaml) if item.extra_vars_path is defined else omit }}"

  loop: "{{ configure_tower_workflows }}"
  when: configure_tower_workflows is defined
  delegate_to: "{{ 'localhost' if tower_local else omit }}"
...
