---
configure_controller_execution_environments:
  - name: "ee-casc"
    image: automationhub.bcnconsulting.com/ee-casc
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"

  - name: "ee-xlsx"
    image: automationhub.bcnconsulting.com/ee-xlsx
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"
...
