---
controller_inventories:
  - name: "{{ orgs }} Localhost"
    description: "Inventory for the Localhost"
    organization: "{{ orgs }}"

  - name: "InventaryExcel"
    description: "Inventory Taken from excel file"
    organization: "{{ orgs }}"

  - name: "SmartInventory URGENT CHANGES CPD BCN Org1"
    description: "SmartInventory CPD BCN Org1"
    host_filter: "groups__name=Patching_cpd_bcn and groups__name=Patching_os_entorno_{{ env }} and groups__name=Patching_os_vendor_redhat and groups__name=Patching_area_ts01 and groups__name=Patching_parcheo_ch_planif_ch00001"
    kind: smart
    organization: "{{ orgs }}"

  - name: "SmartInventory CPD BCN Org1"
    description: "SmartInventory CPD BCN Org1"
    host_filter: "groups__name=Patching_cpd_bcn and groups__name=Patching_os_entorno_{{ env }} and groups__name=Patching_os_vendor_redhat and groups__name=Patching_area_ts01"
    kind: smart
    organization: "{{ orgs }}"

  - name: "SmartInventory CPD MAD Org1"
    description: "SmartInventory CPD MAD Org1"
    host_filter: "groups__name=Patching_cpd_mad and groups__name=Patching_os_entorno_{{ env }} and groups__name=Patching_os_vendor_redhat and groups__name=Patching_area_ts01"
    kind: smart
    organization: "{{ orgs }}"

  - name: "SmartInventory CPD BCN Org2"
    description: "SmartInventory CPD BCN Org2"
    host_filter: "groups__name=Patching_cpd_bcn and groups__name=Patching_os_entorno_{{ env }} and groups__name=Patching_os_vendor_redhat and groups__name=Patching_area_ts02"
    kind: smart
    organization: "{{ orgs }}"

  - name: "SmartInventory CPD MAD Org2"
    description: "SmartInventory CPD MAD Org2"
    host_filter: "groups__name=Patching_cpd_mad and groups__name=Patching_os_entorno_{{ env }} and groups__name=Patching_os_vendor_redhat and groups__name=Patching_area_ts02"
    kind: smart
    organization: "{{ orgs }}"
...
