---
controller_execution_environments:
  - name: "ee-casc"
    image: automationhub.bcnconsulting.com/ee-casc:latest
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"

  - name: "ee-xlsx"
    image: automationhub.bcnconsulting.com/ee-xlsx:latest
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"

  - name: "test-ee-xlsx"
    image: automationhub.bcnconsulting.com/test-ee-xlsx:0.2
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"
...
