---
controller_execution_environments:
  - name: "ee-casc"
    image: demo-hub1-dev.bcnconsulting.com/ee-casc:latest
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"
...
